package com.vedadb.driver;

import com.fasterxml.jackson.databind.JsonNode;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * JDBC Statement implementation for VedaDB.
 */
public class VedaStatement implements Statement {

    protected final VedaConnection connection;
    protected final VedaDBProtocol protocol;
    protected boolean closed = false;
    protected boolean poolable = false;
    protected int maxFieldSize = 0;
    protected int maxRows = 0;
    protected int queryTimeout = 0;
    protected ResultSet currentResultSet;
    protected int updateCount = -1;

    VedaStatement(VedaConnection connection, VedaDBProtocol protocol) {
        this.connection = connection;
        this.protocol = protocol;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();
        connection.ensureTransaction();
        try {
            JsonNode result = protocol.query(sql, null);
            currentResultSet = new VedaResultSet(this, result);
            updateCount = -1;
            return currentResultSet;
        } catch (VedaDBException e) {
            throw new SQLException(e.getMessage(), e);
        }
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        checkOpen();
        connection.ensureTransaction();
        try {
            JsonNode result = protocol.query(sql, null);
            updateCount = result.path("row_count").asInt(0);
            currentResultSet = null;
            return updateCount;
        } catch (VedaDBException e) {
            throw new SQLException(e.getMessage(), e);
        }
    }

    @Override
    public void close() throws SQLException {
        closed = true;
        if (currentResultSet != null) {
            currentResultSet.close();
            currentResultSet = null;
        }
    }

    @Override
    public int getMaxFieldSize() throws SQLException { return maxFieldSize; }
    @Override
    public void setMaxFieldSize(int max) throws SQLException { this.maxFieldSize = max; }
    @Override
    public int getMaxRows() throws SQLException { return maxRows; }
    @Override
    public void setMaxRows(int max) throws SQLException { this.maxRows = max; }
    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {}
    @Override
    public int getQueryTimeout() throws SQLException { return queryTimeout; }
    @Override
    public void setQueryTimeout(int seconds) throws SQLException { this.queryTimeout = seconds; }
    @Override
    public void cancel() throws SQLException {}
    @Override
    public SQLWarning getWarnings() throws SQLException { return null; }
    @Override
    public void clearWarnings() throws SQLException {}
    @Override
    public void setCursorName(String name) throws SQLException {}

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        // Try as query first
        try {
            ResultSet rs = executeQuery(sql);
            return rs != null;
        } catch (SQLException e) {
            // May be an update
            executeUpdate(sql);
            return false;
        }
    }

    @Override
    public ResultSet getResultSet() throws SQLException { return currentResultSet; }
    @Override
    public int getUpdateCount() throws SQLException { return updateCount; }
    @Override
    public boolean getMoreResults() throws SQLException {
        currentResultSet = null;
        updateCount = -1;
        return false;
    }
    @Override
    public void setFetchDirection(int direction) throws SQLException {}
    @Override
    public int getFetchDirection() throws SQLException { return ResultSet.FETCH_FORWARD; }
    @Override
    public void setFetchSize(int rows) throws SQLException {}
    @Override
    public int getFetchSize() throws SQLException { return 0; }
    @Override
    public int getResultSetConcurrency() throws SQLException { return ResultSet.CONCUR_READ_ONLY; }
    @Override
    public int getResultSetType() throws SQLException { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override
    public void addBatch(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("Batch not supported in Statement");
    }
    @Override
    public void clearBatch() throws SQLException {}
    @Override
    public int[] executeBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("Batch not supported in Statement");
    }
    @Override
    public Connection getConnection() throws SQLException { return connection; }
    @Override
    public boolean getMoreResults(int current) throws SQLException { return getMoreResults(); }
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override
    public int getResultSetHoldability() throws SQLException { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }
    @Override
    public void setPoolable(boolean poolable) throws SQLException { this.poolable = poolable; }
    @Override
    public boolean isPoolable() throws SQLException { return poolable; }
    @Override
    public void closeOnCompletion() throws SQLException {}
    @Override
    public boolean isCloseOnCompletion() throws SQLException { return false; }
    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException { return false; }

    protected void checkOpen() throws SQLException {
        if (closed) throw new SQLException("Statement is closed");
        if (connection.isClosed()) throw new SQLException("Connection is closed");
    }
}
